version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    container_name: beibootserver
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: beibootclient
